#+TITLE: Code
#+HTML <categories>code</categories>

** Dashboard Builder

A framework for building up interactive html dashboards in ruby. Contains implementation of both simple & multivariate regression for visualizing trends, fetching email attachments/content as data sources, also allows for posting the end result onto a confluence wiki page.

[[https://github.com/al3xandr3/Dashboard][*code*]] - [[http://al3xandr3.github.com/2011/05/24/dashboards.html][web]] - /June 2011/ - Tools: Ruby, Javascript, Html

-------------------------------

** Linear & Logistic Regression 

A collection of exercises from the OpenClassRoom machine learning classes. Serve as a reference in implementing linear and logistic regression with some added debugging features in R.

- linear regression: [[http://al3xandr3.github.com/2011/02/24/ml-ex2-linear-regression.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml2.r][code]]
- multivariate linear regression: [[http://al3xandr3.github.com/2011/03/08/ml-ex3.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml3.r][code]]
- logistic regression and Newton's method: [[http://al3xandr3.github.com/2011/03/16/ml-ex4.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml4.r][code]]
- regularized linear regression: [[http://al3xandr3.github.com/2011/03/18/ml-ex51.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml5lin.r][code]]
- regularized logistic regression: [[http://al3xandr3.github.com/2011/03/20/ml-ex52.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml5log.r][code]]

/March 2011/ - Tools: R

-------------------------------

** cov3 - Web Crawler Tester

A clojure, selenium based web crawler with a couple of variations that i found useful. Cov3 crawls pages with the intention of executing (javascript)tests/validations on each of the pages it opens. The original idea of a web crawler is that given an initial page it keeps on following all links it finds in the same domain until all pages are visited. I added a couple of variations: Given a sitemap.xml it randomly samples part of it(useful for big sitemaps) and follows those urls executing some test. And another option is a csv file, with the urls and tests to execute on each.

 [[https://github.com/al3xandr3/cov3][*code*]] - [[http://al3xandr3.github.com/2010/05/22/clojure-selenium2-crawler-cov3.html][web]] - /May 2010/ - Tools: clojure, selenium

-------------------------------

** jQuery Twitter 'mini’ plugin

A jQuery plugin to display a twitter feed on a web page(blog for example). The twitter api feed, i found, has an annoying particularity of not always returning the requested number of tweets, so i added a feature that until it gets the right amount of messages it keeps on fetching. Thats useful when you want to fill a web page space with exactly 3 messages.
Also included a "time ago" date calculations based of john resig [[http://ejohn.org/blog/javascript-pretty-date/][code]], with an added local timezone shift.

 [[https://github.com/al3xandr3/jquery-twitter-plugin][*code*]] - [[http://al3xandr3.github.com/2010/04/10/jquery-twitter-plugin.html][web]] - /April 2010/ - Tools: javascript, jquery

-------------------------------

** The Daily Extract

Scripts that automate the process of aggregating data in a database, extracting it, outputting results into csv files and sending them over by sftp. Very feature rich: task list queue, full logging, email reports, sql templating, sftp support, extract volume validation, unit testing. And with a strong convention over configuration theme. 

In Aug 2009 i did a somewhat similar 2nd version of the daily extract, but this time using clojure, with added features: web front end for task queue manipulation, statistics on extracted volumes and sqlite for storing the task list queue and statistics over time.

[[https://github.com/al3xandr3/daily-extract][*code*]] - /2007&2009/ - Tools: ruby, jruby, clojure
