#+TITLE: Code
#+HTML <categories>code</categories>

** Linear & Logistic Regression 

These are a collection of exercises from OpenClassRoom machine learning classes. But serve as a good reference in translating math into code and in using matrix calculations in R. A next step could be building them into a reusable library. /Tool: R/
- linear regression: [[http://al3xandr3.github.com/2011/02/24/ml-ex2-linear-regression.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml2.r][code]]
- multivariate linear regression: [[http://al3xandr3.github.com/2011/03/08/ml-ex3.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml3.r][code]]
- logistic regression and Newton's method: [[http://al3xandr3.github.com/2011/03/16/ml-ex4.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml4.r][code]]
- regularized linear regression: [[http://al3xandr3.github.com/2011/03/18/ml-ex51.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml5lin.r][code]]
- regularized logistic regression: [[http://al3xandr3.github.com/2011/03/20/ml-ex52.html][web]], [[https://github.com/al3xandr3/al3xandr3.github.com/blob/master/_org/posts/ml5log.r][code]]

/March 2011/

-------------------------------

** jQuery Twitter 'mini’ plugin

A jQuery plugin to display a twitter feed on a web page(blog for example). The twitter api feed, i found, has an annoying particularity of not always returning the number of tweets requested, so i added a feature that until it gets the right amount of messages it keeps on fetching. Thats useful when you plan to fill a web page with exactly 3 messages.
Also added a "time ago" date calculations based of john resig [[http://ejohn.org/blog/javascript-pretty-date/][code]], with an added local timezone shift.
/Tools: javascript, jquery/

[[http://al3xandr3.github.com/2010/04/10/jquery-twitter-plugin.html][web]], [[https://github.com/al3xandr3/jquery-twitter-plugin][*code*]], /April 2010/

-------------------------------

** cov3 - Web Crawler Tester

A clojure, selenium based web crawler with a couple of variations that i found useful. Cov3 crawls pages with the intention of executing (javascript)tests/validations on each of the pages it opens. The original idea of a web crawler is that given an initial page it keeps on following all links it finds in the same domain until all pages are visited. I added a couple of variations: Given a sitemap.xml it randomly samples part of it(useful for big sitemaps) and follows those urls executing some test. And another option is a csv file, with the urls and tests to execute on each.
/Tools: clojure, java, selenium/

[[http://al3xandr3.github.com/2010/05/22/clojure-selenium2-crawler-cov3.html][web]], [[https://github.com/al3xandr3/cov3][*code*]], /May 2010/
