#+TITLE: On Tools. Featuring guitar pedals, cattle growing and math.
#+HTML: <category> mathematics matlab guitar </category>
#+OPTIONS: timestamp:nil

Bear with me during all the technical and guitar lingo, and keep reading as there's a point.

* The Plan

After few last weeks of obsessively investigating guitar gear, because of: "what to get this year for my bday?" i decided to change my guitar setup approach, so stop trying to mix "tube sound pureness" with "digital flexibility" all in one. And create 2 distinct setups, that focus on their strengths. A simple all analog-tube beautiful sounding real thing and then separately use pc guitar amps(that don't sound so real) but have all the flexibility in the world.
In the process I removed all the digital pedals from the analog setup and ended up with only 1 analog effect, so i thought: maybe i should get now a couple more analog pedals, for more variety. Or even more special would be to build my own pedal that i could tweak and make unique... Sounds like a plan.

* Do i need to Grow Cattle?

After a little net browsing on DIY analog pedal building, figured out that an analog pedal is not really worth because i will just end up implement some schematic i find from net without the deep understanding of how it all really works and how to develop my own circuits. So maybe i could do instead a software guitar pedal simulation(on my 2nd setup), i can do programming so am in a better position to tweak it to create my own "circuits". Right? wrong! After looking at the mess that audio plugin programming is: incompatible platforms, buffers, headers, new api's to learn, c++ pointers and sharp edges, etc... and not so much about the musical details, I concluded is not really rewarding in the long term because most of the effort is on the wrong things... Is like wanting to make my own  quattro formaggi(4 cheese) pizza, without cheese, so i would need to learn how to grow cattle, get the milk and make the cheese. When what i really want, is play to around with the ingredients and types of cheese to create my own version of this pizza.

* Finding Gold

At some point landed on a page that described mathematical models of "amplifier tubes behavior" and thought, here's something interesting, modeling the behavior of a real tube sound quality sounds like a great idea for a guitar pedal simulation, lets implement this? But wait a minute, implementing it is actually just monkey work, i.e. nothing new about implementing a simple math formula in a programming language and besides most of the effort will unfortunately be around the the audio plugin programming(growing cattle). And on top of that, even if i do it, it will only be running for a couple of years, because when a new audio plugin platform arrives, i will have to do it again...

But lets look at the Math modeling work, first, modeling a tube is all about simulating a real sound circuit behavior(so is focused on the right thing) and second the result of this work is a theoretical model that can be implemented in any computer simulation or even in a stand alone digital chip. So, unlike the audio plugin implementation, the math modeling work is truly platform independent and without expiration date, this is the real gold.

* Making it Real

But then again, just the Math by itself will not make my new guitar pedal, so we still need something else that will implement that theoretical model into some platform... 
I continue to web surfing and by accident found some guitar effects simulations made in Matlab, looked at the source code... Brilliant! Short and directly to the point. High level algorithm implementation of audio effects... This will allow to try out the tubes math models i found before much easier/quicker than with the audio plugin development.
Matlab of course has tradeoffs compared to use the enterprise standard of audio plugin development, is not really suited for building a production-style-final-product, is instead better used for creating a working prototype, that verifies if the theoretical ideas really work. So later on, if i want to sell my perfected new software guitar pedal as an production-like end product i will indeed have to Grow Cattle.

*So as promised, the point:* Tools matter, because they can distract you from focusing on the right things. Some Cattle Growing is required, but try keep it to a minimum and focus instead on the gold.
