
require 'rake'

desc 'default'
task :default => :html

desc "html"
task :html do

  # Build the page
  template = %q{
    <html>
    <head>
    <style>
    body {
      font-family: "Segoe UI", Segoe, helvetica, arial;
      padding: 1em;
      color: #4c4c4c;
      padding-bottom: 42px;
      padding-top: 1em;
      margin-left: auto;
      margin-right: auto;
      width: 700px;
      position: relative;
    }
    p {
      max-width: 40em;
    }    
    h1, h2, h3, h4 {
     font-family: "Segoe UI", Segoe, helvetica, arial;
     color: #666;
    }
    thead tr, thead th {
      background: none repeat scroll 0 0 #F0F0F0;
    }
    pre {
      border: 1px solid #D8D8D8;
      background-color: #F7F7F7;
      font: 1em/1.5 'andale mono','lucida console', monospace;
      overflow: auto;
      padding: 1.5em 0em 1.5em !important;
    }
    blockquote {
      border-left: 4px double #CCC;
      font-style: italic;
      padding-left: 1em;
    }
    </style>
    </head>
    <body>
      <%= content %>
      <br /> 
    </body>
    </html>
  }.gsub(/^\s+/, '')

  # markdown to html
  # gem install rdiscount
  content = %x[rdiscount cv.md]

  # remove the blog headlines
  content.gsub!("<hr />\n\n<p>layout: page\ntitle: Curriculum Vitae</p>\n\n<h2>intro: \"Curriculum Vitae\"</h2>","")
  content = "<h1>Curriculum Vitae</h1>\n" + content

  # template
  # gem install erb
  require 'erb'
  page = ERB.new(template, 0, "%<>").result(binding)

  # output
  File.open("cv.html", "w") { |f| f.write(page) } 
end

# http://code.google.com/p/wkhtmltopdf/
desc "pdf"
task :pdf => [:html] do
  system "wkhtmltopdf cv.html cv.pdf"
end

desc "clean"
task :clean do
  system "rm cv.html"
  system "rm cv.pdf"
end
